environment:
  global:
    VisualStudio:     '"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC"'
    libjpeg_version:  "9d"
    libjpeg_files: "http://ijg.org/files/"
  matrix:
  - configuration: release
  # configuration: debug
  
platform:
  #- x86
  - amd64

init:
  - '%VisualStudio%\vcvarsall.bat %platform%'

install:
  # Get libjpeg source 
  - appveyor DownloadFile %Libjpeg_files%/jpegsr%libjpeg_version%.zip
  - 7z x jpegsr%libjpeg_version%.zip
  - move win32.mak jpeg-%libjpeg_version%
  # mkdir zlib
  # cd zlib
  #- appveyor DownloadFile https://github.com/maxirmx/Dist_zlib/releases/latest/download/zlib-%platform%-%configuration%.zip
  #- 7z e -tzip zlib-%platform%-%configuration%.zip
  # cd ..
   
build_script:                                                                                   
  # Build
  - cd jpeg-%libjpeg_version%
  - ps: (Get-Content makefile.vs) -replace '#!include <win32.mak>', '!include <win32.mak>' | Out-File -encoding ASCII makefile.vs
  - nmake -f makefile.vs setup-v16
  - nmake -f makefile.vs 
  - dir
  - cd ..
  - mkdir d
  - mkdir d\include
  - mkdir d\lib
  - mkdir d\bin
  - copy jpeg-%libjpeg_version%\*.exe d\bin
  - copy jpeg-%libjpeg_version%\*.lib d\lib
  # copy lpng1634\pngconf.h d\include
  # copy lpng1634\pnginfo.h d\include
  # copy lpng1634\libpng.lib d\lib
  # cd d
  # 7z a -tzip -r -y ..\libpng-%platform%-%configuration%.zip *.*
   
test: off

artifacts:
   #- path: libpng-%platform%-%configuration%.zip
   
deploy:
# provider: GitHub
#  release: $(appveyor_build_version)
#  description: 'libpng build [$(appveyor_build_version)]'
#  auth_token:
#    secure: 7fz/vsEpOOUyPYNmrykrY4lgqu3XQsag6g4x25nOwtd2dM2kc3X3GPoPzMCMDno/
#  draft: false
#  prerelease: false
#  on:
#    branch: master                 # release from master branch only
#    APPVEYOR_REPO_TAG: false       # deploy on tag push only
