environment:
  global:
    VisualStudio:     '"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC"'
    libjpeg_version:  "9d"
    libjpeg_files: "http://ijg.org/files/"
  matrix:
  - configuration: release
  - configuration: debug
  
platform:
  - x86
  - amd64

init:
  - '%VisualStudio%\vcvarsall.bat %platform%'

install:
  # Get libjpeg source 
  - appveyor DownloadFile %Libjpeg_files%/jpegsr%libjpeg_version%.zip
  - 7z x jpegsr%libjpeg_version%.zip
  - move win32.mak jpeg-%libjpeg_version%
   
build_script:                                                                                   
  # Build
  - cd jpeg-%libjpeg_version%
  - ps: (Get-Content makefile.vs) -replace '#!include <win32.mak>', '!include <win32.mak>' | Out-File -encoding ASCII makefile.vs
  - nmake -f makefile.vs CFG=%configuration% setup-v16 
  - nmake -f makefile.vs CFG=%configuration%
  - cd ..
  - mkdir d
  - mkdir d\include
  - mkdir d\lib
  - mkdir d\bin
  - copy jpeg-%libjpeg_version%\*.exe d\bin
  - copy jpeg-%libjpeg_version%\*.lib d\lib
  - copy jpeg-%libjpeg_version%\j*.h d\include
  - cd d
  - 7z a -tzip -r -y ..\libjpeg-%platform%-%configuration%.zip *.*
   
test: off

artifacts:
   - path: libjpeg-%platform%-%configuration%.zip
   
deploy:
- provider: GitHub
# I am tagging through github
# Tag format is v<major version>.<minor version>, shall be consistent with major.monir of Appveyor build
# release: v$(appveyor_build_version)
  description: 'libjpeg AppVeyor build script v$(appveyor_build_version) with binaries'
  auth_token:
    secure: 7fz/vsEpOOUyPYNmrykrY4lgqu3XQsag6g4x25nOwtd2dM2kc3X3GPoPzMCMDno/
  draft: false
  prerelease: false
  on:
    branch: master                 # release from master branch only
    APPVEYOR_REPO_TAG: true        # deploy on tag push only
